version: '3.3'
services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=miniwa
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis.conf:/opt/redis/redis.conf"
    command: "redis-server /opt/redis/redis.conf"
